/**
 * Activity Map data model.
 * Mirrors the structure of `ui/src/assets/data/activities.json`,
 * which is generated by `convert-activities.py`.
 */

export type CategoryId = 'wash' | 'recovery';

export type TypeId =
  | 'water_tower'
  | 'water_purification'
  | 'pumps'
  | 'pipes'
  | 'water_tanks'
  | 'wash_facility_rehab'
  | 'borehole_drilling'
  | 'roof_replacement'
  | 'windows_doors_replacement'
  | 'windows_replacement';

export type InstitutionType = 'educational' | 'medical' | 'cultural' | 'community' | 'other';

export type Lang = 'uk' | 'en';

export interface LocalizedText {
  uk: string;        // required
  en?: string;       // optional, frontend falls back to uk
}

export interface Coordinates {
  lat: number;
  lng: number;
}

export interface Institution {
  name: LocalizedText;
  type: InstitutionType;
}

export interface ActivityLocation {
  region: LocalizedText | null;
  district: LocalizedText | null;
  community: LocalizedText | null;
  settlement: LocalizedText | null;
  institution: Institution | null;
  coordinates: Coordinates | null;   // null when GPS data was rejected by converter
}

export interface ActivityCategory {
  id: CategoryId;
  label: LocalizedText;
}

export interface ActivityTypeMeta {
  categoryId: CategoryId;
  label: LocalizedText;
  icon: string;                       // file in ui/src/assets/icons/activities/
  unit: 'pcs' | 'm' | 'm2' | 'facilities';
}

export interface Activity {
  id: string;                         // e.g. "water_tower-001"
  typeId: TypeId;
  donor: string | null;               // UNICEF | LDS | Nadacia Pontis | ...
  completedAt: string | null;         // "YYYY-MM"
  location: ActivityLocation;
  details: LocalizedText | null;
  beneficiaries: number | null;
  residents: number | null;           // not shown publicly on MVP
  evidenceUrl: string | null;         // not shown publicly on MVP
}

export interface ActivityMapData {
  version: string;
  updatedAt: string;
  categories: ActivityCategory[];
  types: Record<TypeId, ActivityTypeMeta>;
  activities: Activity[];
}
