/**
 * Activity Map data model.
 * Mirrors the structure of `ui/src/assets/data/activities.json`,
 * generated by `convert-activities.py`.
 */

export type CategoryId = 'wash' | 'recovery';

export type TypeId =
  | 'water_tower'
  | 'water_purification'
  | 'pumps'
  | 'pipes'
  | 'water_tanks'
  | 'wash_facility_rehab'
  | 'borehole_drilling'
  | 'roof_replacement'
  | 'windows_doors_replacement'
  | 'windows_replacement';

export type InstitutionType =
  | 'educational'
  | 'medical'
  | 'cultural'
  | 'community'
  | 'other';

export type Lang = 'uk' | 'en';

export interface LocalizedText {
  uk: string;
  en?: string;
}

export interface Coordinates {
  lat: number;
  lng: number;
}

export interface Institution {
  name: LocalizedText;
  type: InstitutionType;
}

export interface ActivityLocation {
  region: LocalizedText | null;
  district: LocalizedText | null;
  community: LocalizedText | null;
  settlement: LocalizedText | null;
  institution: Institution | null;
  coordinates: Coordinates | null;
}

export interface ActivityCategory {
  id: CategoryId;
  label: LocalizedText;
}

export interface ActivityTypeMeta {
  categoryId: CategoryId;
  label: LocalizedText;
  icon: string;
  unit: 'pcs' | 'm' | 'm2' | 'facilities';
}

export interface Activity {
  id: string;
  typeId: TypeId;
  donor: string | null;
  completedAt: string | null;
  location: ActivityLocation;
  details: LocalizedText | null;
  beneficiaries: number | null;
  residents: number | null;
  evidenceUrl: string | null;
}

export interface ActivityMapData {
  version: string;
  updatedAt: string;
  categories: ActivityCategory[];
  types: Record<TypeId, ActivityTypeMeta>;
  activities: Activity[];
}
